### ISSUE TITLE
Crash on build that has proguard enabled

### ISSUE THREAD

**Issue by gaborbiro** [Instabug/Instabug-Android#296]
### Steps to Reproduce the Problem
My proguard-minfied and shrinked build crashes on launch.
Works fine without minify/shrink.
Minified&shrinked build worked fine until 9.1.0. Broke after updating to 9.1.1
My proguard rules don't have anything Instabug-related

### Instabug integration code
```
        Instabug.Builder(this, getString(R.string.instabug_key))
            .setInvocationEvents(
                InstabugInvocationEvent.SHAKE,
                InstabugInvocationEvent.TWO_FINGER_SWIPE_LEFT
            )
            .setReproStepsState(State.ENABLED)
            .build()

        Instabug.setDebugEnabled(BuildConfig.DEBUG)
        Instabug.setTrackingUserStepsState(Feature.State.ENABLED)
        if (BuildConfig.DEBUG) {
            Instabug.setWelcomeMessageState(WelcomeMessage.State.BETA)
        } else {
            Instabug.setWelcomeMessageState(WelcomeMessage.State.LIVE)
        }
        Replies.setPushNotificationChannelId(getString(R.string.default_notification_channel_id))
        Replies.setNotificationIcon(R.drawable.brand_logo)
        Replies.setPushNotificationState(Feature.State.ENABLED)
        Replies.setSystemReplyNotificationSoundEnabled(true)
        Replies.setShouldPlayConversationSounds(false)
```

### SDK Version
9.1.1

### Android Version
Android 10

### Device Model
Pixel 2 XL

### Crash stacktrace (de-obfuscated it as much as I could)
```
 Process: com.luminixmarketing.vemely.test, PID: 5538
    io.reactivex.exceptions.UndeliverableException: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/instabug/library/user/UserManager;
        at io.reactivex.plugins.RxJavaPlugins.onError(SourceFile:8)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(SourceFile:3)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(SourceFile:1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/instabug/library/user/UserManager;
        at com.instabug.chat.synchronization.a.a(SourceFile:50)
        at com.instabug.chat.synchronization.a.a(SourceFile:1)
        at com.instabug.chat.synchronization.SynchronizationManager.handleReceivedMessages(SourceFile:7)
        at com.instabug.chat.synchronization.SynchronizationManager.handleSuccessResponse(SourceFile:6)
        at com.instabug.chat.synchronization.SynchronizationManager.access$300(SourceFile:1)
        at com.instabug.chat.synchronization.SynchronizationManager$c.a(SourceFile:1)
        at com.instabug.chat.synchronization.SynchronizationManager$c.onSucceeded(SourceFile:1)
        at com.instabug.chat.network.c.a$d.a(SourceFile:5)
        at com.instabug.chat.network.c.a$d.onNext(SourceFile:6)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onNext(SourceFile:2)
        at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.onNext(SourceFile:3)
        at com.instabug.library.network.NetworkManager$a.subscribe(SourceFile:16)
        at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(SourceFile:3)
        at io.reactivex.Observable.subscribe(SourceFile:80)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(SourceFile:1)
        at io.reactivex.Scheduler$DisposeTask.run(SourceFile:2)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(SourceFile:2)
        at g.d.z.g.k.call(SourceFile:1) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
     Caused by: java.lang.ClassNotFoundException: com.instabug.library.user.UserManager
        at d.i.b.n.a.a(SourceFile:50) 
        at d.i.b.n.a.a(SourceFile:1) 
        at com.instabug.chat.synchronization.SynchronizationManager.handleReceivedMessages(SourceFile:7) 
        at com.instabug.chat.synchronization.SynchronizationManager.handleSuccessResponse(SourceFile:6) 
        at com.instabug.chat.synchronization.SynchronizationManager.access$300(SourceFile:1) 
        at com.instabug.chat.synchronization.SynchronizationManager$c.a(SourceFile:1) 
        at com.instabug.chat.synchronization.SynchronizationManager$c.onSucceeded(SourceFile:1) 
        at d.i.b.l.c.a$d.a(SourceFile:5) 
        at d.i.b.l.c.a$d.a(SourceFile:6) 
        at g.d.z.e.c.x$a.a(SourceFile:2) 
        at g.d.z.e.c.c$a.a(SourceFile:3) 
        at com.instabug.library.network.NetworkManager$a.a(SourceFile:16) 
        at g.d.z.e.c.c.b(SourceFile:3) 
        at g.d.m.a(SourceFile:80) 
        at g.d.z.e.c.x$b.run(SourceFile:1) 
        at g.d.r$a.run(SourceFile:2) 
        at g.d.z.g.k.run(SourceFile:2) 
        at g.d.z.g.k.call(SourceFile:1) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
```

**Comment by Muhammadyoussef** [comment]
Hi @gaborbiro,

I created a SNAPSHOT for you that has the fix. Please give it a try & let me know if you face any issues.

```
implementation 'com.instabug.library:instabug:9.1.3.5-SNAPSHOT'
```

To consume the SNAPSHOT you will need to add the following to your app `build.gradle`
```
repositories {
    ....
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
```
This SNAPSHOT is completely safe to use and has no debug code at all.

**Comment by Muhammadyoussef** [comment]
Hi @gaborbiro,

Just to let you know, this fix has made it to a stable release. You can now use the latest version of Instabug instead of relying on this snapshot. To consume the changes please update your dependency as follows

​`implementation 'com.instabug.library:instabug:9.1.4'`
