### ISSUE TITLE
App crashes on load with java.lang.NoClassDefFoundError : Failed resolution of: Landroid/support/v4/app/JobIntentService

### ISSUE THREAD

**Issue by dwolvin** [Instabug/Instabug-Android#113]
After upgrading Instabug from 4.7.0 to 8.0.3 the app crashes on load.  
Stack trace:

I/art: Rejecting re-init on previously-failed class java.lang.Class<com.instabug.library.network.a>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/app/JobIntentService;
I/art:     at void com.instabug.crash.CrashPlugin.startCrashesUploaderService() (CrashPlugin.java:86)
I/art:     at void com.instabug.crash.CrashPlugin.access$100(com.instabug.crash.CrashPlugin) (CrashPlugin.java:31)
I/art:     at void com.instabug.crash.CrashPlugin$1.a(com.instabug.library.core.eventbus.coreeventbus.SDKCoreEvent) (CrashPlugin.java:68)
I/art:     at void com.instabug.crash.CrashPlugin$1.accept(java.lang.Object) (CrashPlugin.java:57)
I/art:     at void io.reactivex.internal.observers.LambdaObserver.onNext(java.lang.Object) (LambdaObserver.java:63)
I/art:     at void io.reactivex.subjects.PublishSubject$PublishDisposable.onNext(java.lang.Object) (PublishSubject.java:309)
I/art:     at void io.reactivex.subjects.PublishSubject.onNext(java.lang.Object) (PublishSubject.java:229)
I/art:     at void com.instabug.library.core.eventbus.EventBus.post(java.lang.Object) (EventBus.java:24)
I/art:     at void com.instabug.library.core.eventbus.coreeventbus.SDKCoreEventPublisher.post(com.instabug.library.core.eventbus.coreeventbus.SDKCoreEvent) (SDKCoreEventPublisher.java:9)
I/art:     at void com.instabug.library.e.a(com.instabug.library.model.Session$SessionState) (SessionManager.java:207)
I/art:     at void com.instabug.library.e.d() (SessionManager.java:88)
I/art:     at void com.instabug.library.tracking.a.onActivityResumed(android.app.Activity) (InstabugActivityLifecycleListener.java:30)
I/art:     at void android.app.Application.dispatchActivityResumed(android.app.Activity) (Application.java:216)
I/art:     at void android.app.Activity.onResume() (Activity.java:1251)
I/art:     at void com.teambizwiz.cotg.screen.MainActivity.onResume() (MainActivity.java:411)
I/art:     at void android.app.Instrumentation.callActivityOnResume(android.app.Activity) (Instrumentation.java:1269)
I/art:     at void android.app.Activity.performResume() (Activity.java:6783)
I/art:     at android.app.ActivityThread$ActivityClientRecord android.app.ActivityThread.performResumeActivity(android.os.IBinder, boolean, java.lang.String) (ActivityThread.java:3406)
I/art:     at void android.app.ActivityThread.handleResumeActivity(android.os.IBinder, boolean, boolean, boolean, int, java.lang.String) (ActivityThread.java:3469)
I/art:     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2732)
I/art:     at void android.app.ActivityThread.-wrap12(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
I/art:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1477)
I/art:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
I/art:     at void android.os.Looper.loop() (Looper.java:154)
I/art:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6119)
I/art:     at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/art:     at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:886)
I/art:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:776)
I/art: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.app.JobIntentService" on path: DexPathList[[zip file "/data/app/com.teambizwiz.contractoronthego-1/base.apk"],nativeLibraryDirectories=[/data/app/com.teambizwiz.contractoronthego-1/lib/x86, /data/app/com.teambizwiz.contractoronthego-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]
I/art:     at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/art:     at void com.instabug.crash.CrashPlugin.startCrashesUploaderService() (CrashPlugin.java:86)
I/art:     at void com.instabug.crash.CrashPlugin.access$100(com.instabug.crash.CrashPlugin) (CrashPlugin.java:31)
I/art:     at void com.instabug.crash.CrashPlugin$1.a(com.instabug.library.core.eventbus.coreeventbus.SDKCoreEvent) (CrashPlugin.java:68)
I/art:     at void com.instabug.crash.CrashPlugin$1.accept(java.lang.Object) (CrashPlugin.java:57)
I/art:     at void io.reactivex.internal.observers.LambdaObserver.onNext(java.lang.Object) (LambdaObserver.java:63)
I/art:     at void io.reactivex.subjects.PublishSubject$PublishDisposable.onNext(java.lang.Object) (PublishSubject.java:309)
I/art:     at void io.reactivex.subjects.PublishSubject.onNext(java.lang.Object) (PublishSubject.java:229)
I/art:     at void com.instabug.library.core.eventbus.EventBus.post(java.lang.Object) (EventBus.java:24)
I/art:     at void com.instabug.library.core.eventbus.coreeventbus.SDKCoreEventPublisher.post(com.instabug.library.core.eventbus.coreeventbus.SDKCoreEvent) (SDKCoreEventPublisher.java:9)
I/art:     at void com.instabug.library.e.a(com.instabug.library.model.Session$SessionState) (SessionManager.java:207)
I/art:     at void com.instabug.library.e.d() (SessionManager.java:88)
I/art:     at void com.instabug.library.tracking.a.onActivityResumed(android.app.Activity) (InstabugActivityLifecycleListener.java:30)
I/art:     at void android.app.Application.dispatchActivityResumed(android.app.Activity) (Application.java:216)
I/art:     at void android.app.Activity.onResume() (Activity.java:1251)
I/art:     at void com.teambizwiz.cotg.screen.MainActivity.onResume() (MainActivity.java:411)
I/art:     at void android.app.Instrumentation.callActivityOnResume(android.app.Activity) (Instrumentation.java:1269)
I/art:     at void android.app.Activity.performResume() (Activity.java:6783)
I/art:     at android.app.ActivityThread$ActivityClientRecord android.app.ActivityThread.performResumeActivity(android.os.IBinder, boolean, java.lang.String) (ActivityThread.java:3406)
I/art:     at void android.app.ActivityThread.handleResumeActivity(android.os.IBinder, boolean, boolean, boolean, int, java.lang.String) (ActivityThread.java:3469)
I/art:     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2732)
I/art:     at void android.app.ActivityThread.-wrap12(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
I/art:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1477)
I/art:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
I/art:     at void android.os.Looper.loop() (Looper.java:154)
I/art:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6119)
I/art:     at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/art:     at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:886)
I/art:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:776)
I/art: Rejecting re-init on previously-failed class java.lang.Class<com.instabug.library.network.InstabugNetworkBasedBackgroundService>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/instabug/library/network/a;
I/art:     at void com.instabug.crash.CrashPlugin.startCrashesUploaderService() (CrashPlugin.java:86)
I/art:     at void com.instabug.crash.CrashPlugin.access$100(com.instabug.crash.CrashPlugin) (CrashPlugin.java:31)
I/art:     at void com.instabug.crash.CrashPlugin$1.a(com.instabug.library.core.eventbus.coreeventbus.SDKCoreEvent) (CrashPlugin.java:68)
I/art:     at void com.instabug.crash.CrashPlugin$1.accept(java.lang.Object) (CrashPlugin.java:57)
I/art:     at void io.reactivex.internal.observers.LambdaObserver.onNext(java.lang.Object) (LambdaObserver.java:63)
I/art:     at void io.reactivex.subjects.PublishSubject$PublishDisposable.onNext(java.lang.Object) (PublishSubject.java:309)
I/art:     at void io.reactivex.subjects.PublishSubject.onNext(java.lang.Object) (PublishSubject.java:229)
I/art:     at void com.instabug.library.core.eventbus.EventBus.post(java.lang.Object) (EventBus.java:24)
I/art:     at void com.instabug.library.core.eventbus.coreeventbus.SDKCoreEventPublisher.post(com.instabug.library.core.eventbus.coreeventbus.SDKCoreEvent) (SDKCoreEventPublisher.java:9)
I/art:     at void com.instabug.library.e.a(com.instabug.library.model.Session$SessionState) (SessionManager.java:207)
I/art:     at void com.instabug.library.e.d() (SessionManager.java:88)
I/art:     at void com.instabug.library.tracking.a.onActivityResumed(android.app.Activity) (InstabugActivityLifecycleListener.java:30)
I/art:     at void android.app.Application.dispatchActivityResumed(android.app.Activity) (Application.java:216)
I/art:     at void android.app.Activity.onResume() (Activity.java:1251)
I/art:     at void com.teambizwiz.cotg.screen.MainActivity.onResume() (MainActivity.java:411)
I/art:     at void android.app.Instrumentation.callActivityOnResume(android.app.Activity) (Instrumentation.java:1269)
I/art:     at void android.app.Activity.performResume() (Activity.java:6783)
I/art:     at android.app.ActivityThread$ActivityClientRecord android.app.ActivityThread.performResumeActivity(android.os.IBinder, boolean, java.lang.String) (ActivityThread.java:3406)
I/art:     at void android.app.ActivityThread.handleResumeActivity(android.os.IBinder, boolean, boolean, boolean, int, java.lang.String) (ActivityThread.java:3469)
I/art:     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2732)
I/art:     at void android.app.ActivityThread.-wrap12(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
I/art:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1477)
I/art:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
I/art:     at void android.os.Looper.loop() (Looper.java:154)
I/art:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6119)
I/art:     at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/art:     at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:886)
I/art:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:776)
I/art: Caused by: java.lang.ClassNotFoundException: com.instabug.library.network.a
I/art:     at java.lang.Class java.lang.VMClassLoader.findLoadedClass!(java.lang.ClassLoader, java.lang.String) (VMClassLoader.java:-2)
I/art:     at java.lang.Class java.lang.ClassLoader.findLoadedClass(java.lang.String) (ClassLoader.java:742)
I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:362)
I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/art:     at void com.instabug.crash.CrashPlugin.startCrashesUploaderService() (CrashPlugin.java:86)
I/art:     at void com.instabug.crash.CrashPlugin.access$100(com.instabug.crash.CrashPlugin) (CrashPlugin.java:31)
I/art:     at void com.instabug.crash.CrashPlugin$1.a(com.instabug.library.core.eventbus.coreeventbus.SDKCoreEvent) (CrashPlugin.java:68)
I/art:     at void com.instabug.crash.CrashPlugin$1.accept(java.lang.Object) (CrashPlugin.java:57)
I/art:     at void io.reactivex.internal.observers.LambdaObserver.onNext(java.lang.Object) (LambdaObserver.java:63)
I/art:     at void io.reactivex.subjects.PublishSubject$PublishDisposable.onNext(java.lang.Object) (PublishSubject.java:309)
I/art:     at void io.reactivex.subjects.PublishSubject.onNext(java.lang.Object) (PublishSubject.java:229)
I/art:     at void com.instabug.library.core.eventbus.EventBus.post(java.lang.Object) (EventBus.java:24)
I/art:     at void com.instabug.library.core.eventbus.coreeventbus.SDKCoreEventPublisher.post(com.instabug.library.core.eventbus.coreeventbus.SDKCoreEvent) (SDKCoreEventPublisher.java:9)
I/art:     at void com.instabug.library.e.a(com.instabug.library.model.Session$SessionState) (SessionManager.java:207)
I/art:     at void com.instabug.library.e.d() (SessionManager.java:88)
I/art:     at void com.instabug.library.tracking.a.onActivityResumed(android.app.Activity) (InstabugActivityLifecycleListener.java:30)
I/art:     at void android.app.Application.dispatchActivityResumed(android.app.Activity) (Application.java:216)
I/art:     at void android.app.Activity.onResume() (Activity.java:1251)
I/art:     at void com.teambizwiz.cotg.screen.MainActivity.onResume() (MainActivity.java:411)
I/art:     at void android.app.Instrumentation.callActivityOnResume(android.app.Activity) (Instrumentation.java:1269)
I/art:     at void android.app.Activity.performResume() (Activity.java:6783)
I/art:     at android.app.ActivityThread$ActivityClientRecord android.app.ActivityThread.performResumeActivity(android.os.IBinder, boolean, java.lang.String) (ActivityThread.java:3406)
I/art:     at void android.app.ActivityThread.handleResumeActivity(android.os.IBinder, boolean, boolean, boolean, int, java.lang.String) (ActivityThread.java:3469)
I/art:     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2732)
I/art:     at void android.app.ActivityThread.-wrap12(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
I/art:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1477)
I/art:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
I/art:     at void android.os.Looper.loop() (Looper.java:154)
I/art:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6119)
I/art:     at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/art:     at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:886)
I/art:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:776)
I/art: Rejecting re-init on previously-failed class java.lang.Class<com.instabug.crash.network.InstabugCrashesUploaderService>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/instabug/library/network/InstabugNetworkBasedBackgroundService;
I/art:     at void com.instabug.crash.CrashPlugin.startCrashesUploaderService() (CrashPlugin.java:86)
I/art:     at void com.instabug.crash.CrashPlugin.access$100(com.instabug.crash.CrashPlugin) (CrashPlugin.java:31)
I/art:     at void com.instabug.crash.CrashPlugin$1.a(com.instabug.library.core.eventbus.coreeventbus.SDKCoreEvent) (CrashPlugin.java:68)
I/art:     at void com.instabug.crash.CrashPlugin$1.accept(java.lang.Object) (CrashPlugin.java:57)
I/art:     at void io.reactivex.internal.observers.LambdaObserver.onNext(java.lang.Object) (LambdaObserver.java:63)
I/art:     at void io.reactivex.subjects.PublishSubject$PublishDisposable.onNext(java.lang.Object) (PublishSubject.java:309)
I/art:     at void io.reactivex.subjects.PublishSubject.onNext(java.lang.Object) (PublishSubject.java:229)
I/art:     at void com.instabug.library.core.eventbus.EventBus.post(java.lang.Object) (EventBus.java:24)
I/art:     at void com.instabug.library.core.eventbus.coreeventbus.SDKCoreEventPublisher.post(com.instabug.library.core.eventbus.coreeventbus.SDKCoreEvent) (SDKCoreEventPublisher.java:9)
I/art:     at void com.instabug.library.e.a(com.instabug.library.model.Session$SessionState) (SessionManager.java:207)
I/art:     at void com.instabug.library.e.d() (SessionManager.java:88)
I/art:     at void com.instabug.library.tracking.a.onActivityResumed(android.app.Activity) (InstabugActivityLifecycleListener.java:30)
I/art:     at void android.app.Application.dispatchActivityResumed(android.app.Activity) (Application.java:216)
I/art:     at void android.app.Activity.onResume() (Activity.java:1251)
I/art:     at void com.teambizwiz.cotg.screen.MainActivity.onResume() (MainActivity.java:411)
I/art:     at void android.app.Instrumentation.callActivityOnResume(android.app.Activity) (Instrumentation.java:1269)
I/art:     at void android.app.Activity.performResume() (Activity.java:6783)
I/art:     at android.app.ActivityThread$ActivityClientRecord android.app.ActivityThread.performResumeActivity(android.os.IBinder, boolean, java.lang.String) (ActivityThread.java:3406)
I/art:     at void android.app.ActivityThread.handleResumeActivity(android.os.IBinder, boolean, boolean, boolean, int, java.lang.String) (ActivityThread.java:3469)
I/art:     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2732)
I/art:     at void android.app.ActivityThread.-wrap12(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
I/art:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1477)
I/art:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
I/art:     at void android.os.Looper.loop() (Looper.java:154)
I/art:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6119)
I/art:     at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/art:     at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:886)
I/art:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:776)
I/art: Caused by: java.lang.ClassNotFoundException: com.instabug.library.network.InstabugNetworkBasedBackgroundService
I/art:     at java.lang.Class java.lang.VMClassLoader.findLoadedClass!(java.lang.ClassLoader, java.lang.String) (VMClassLoader.java:-2)
I/art:     at java.lang.Class java.lang.ClassLoader.findLoadedClass(java.lang.String) (ClassLoader.java:742)
I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:362)
I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/art:     at void com.instabug.crash.CrashPlugin.startCrashesUploaderService() (CrashPlugin.java:86)
I/art:     at void com.instabug.crash.CrashPlugin.access$100(com.instabug.crash.CrashPlugin) (CrashPlugin.java:31)
I/art:     at void com.instabug.crash.CrashPlugin$1.a(com.instabug.library.core.eventbus.coreeventbus.SDKCoreEvent) (CrashPlugin.java:68)
I/art:     at void com.instabug.crash.CrashPlugin$1.accept(java.lang.Object) (CrashPlugin.java:57)
I/art:     at void io.reactivex.internal.observers.LambdaObserver.onNext(java.lang.Object) (LambdaObserver.java:63)
I/art:     at void io.reactivex.subjects.PublishSubject$PublishDisposable.onNext(java.lang.Object) (PublishSubject.java:309)
I/art:     at void io.reactivex.subjects.PublishSubject.onNext(java.lang.Object) (PublishSubject.java:229)
I/art:     at void com.instabug.library.core.eventbus.EventBus.post(java.lang.Object) (EventBus.java:24)
I/art:     at void com.instabug.library.core.eventbus.coreeventbus.SDKCoreEventPublisher.post(com.instabug.library.core.eventbus.coreeventbus.SDKCoreEvent) (SDKCoreEventPublisher.java:9)
I/art:     at void com.instabug.library.e.a(com.instabug.library.model.Session$SessionState) (SessionManager.java:207)
I/art:     at void com.instabug.library.e.d() (SessionManager.java:88)
I/art:     at void com.instabug.library.tracking.a.onActivityResumed(android.app.Activity) (InstabugActivityLifecycleListener.java:30)
I/art:     at void android.app.Application.dispatchActivityResumed(android.app.Activity) (Application.java:216)
I/art:     at void android.app.Activity.onResume() (Activity.java:1251)
I/art:     at void com.teambizwiz.cotg.screen.MainActivity.onResume() (MainActivity.java:411)
I/art:     at void android.app.Instrumentation.callActivityOnResume(android.app.Activity) (Instrumentation.java:1269)
I/art:     at void android.app.Activity.performResume() (Activity.java:6783)
I/art:     at android.app.ActivityThread$ActivityClientRecord android.app.ActivityThread.performResumeActivity(android.os.IBinder, boolean, java.lang.String) (ActivityThread.java:3406)
I/art:     at void android.app.ActivityThread.handleResumeActivity(android.os.IBinder, boolean, boolean, boolean, int, java.lang.String) (ActivityThread.java:3469)
I/art:     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2732)
I/art:     at void android.app.ActivityThread.-wrap12(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
I/art:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1477)
I/art:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
I/art:     at void android.os.Looper.loop() (Looper.java:154)
I/art:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6119)
I/art:     at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/art:     at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:886)
I/art:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:776)
D/AndroidRuntime: Shutting down VM

**Comment by Korazy** [comment]
Hey @dwolvin 

Thanks for reaching out with this. We'll look into it and get back to you :)

**Comment by Korazy** [comment]
So the issue here is we use `JobIntentService` that is included in the v4 supports library of newer version than version 25. You would need to upgrade your support library to a newer version in order to stop the crashes.
